require("opa-js-runtime-cps");
require("opabsl.opp");
require("calendar.view.opx");
var ___server_ast_f20327e6 = BslCps_topwait(___register_server_code_ec6de8cf({package_:"calendar.controller",adhoc_e:[{td:[],rd:[],r:[true],id:["`_v1_dispatcher_calendar.controller`","`_v1_start_stdlib.core.web.server`"],i:{some:"`_v1__do__calendar.controller`"},d:js_void,c:{none:js_void}},{td:[],rd:[],r:[false],id:["`_v1_dispatcher_calendar.controller`"],i:{some:"`_v1_Controller_calendar.controller`"},d:js_void,c:{none:js_void}},{td:[],rd:[],r:[false],id:["`_v1_login_screen_calendar.view`","`_v1_map_screen_calendar.view`"],i:{some:"`_v1_dispatcher_calendar.controller`"},d:js_void,c:{none:js_void}}]},cont(BslCps_topk)));
var ___static_include_resource_f20327e6 = BslCps_topwait(___make_resource_include_01d140d3("resources/css/style.css",{misc:js_void},___of_base64_skip_ec6de8cf("CiNzZXJ2aWNlLCAjc3luYywgI3ByZWYgewoJbWFyZ2luLXRvcDoxMHB4Owp9Cgp0ZXh0YXJlYSB7CiAgICB3aWR0aDogMTAwJTsKfQoKLmNlbGx7Cglmb250LXNpemU6MjJweDsKCWJhY2tncm91bmQtY29sb3I6I0ZGRjsKCXBhZGRpbmc6MTBweDsKCXBhZGRpbmctdG9wOjE1cHg7CglwYWRkaW5nLWJvdHRvbToxNXB4Owp9CgouY2VsbDpob3ZlcnsKCWJhY2tncm91bmQtY29sb3I6I0VGRUZFRjsKCWN1cnNvcjpwb2ludGVyOwp9Ci5jZWxsIGJ7CglwYWRkaW5nOjEwcHg7Cn0KCi5vdGhlck1vbnRoewoJY29sb3I6I2JmYmZiZjsKfQo="),false,false,{permanent:js_void},__v15_an_01d140d3("text/css"),cont(BslCps_topk)));
global.___dispatcher_f20327e6 = function ___dispatcher_f20327e6(a,b){var d,c;return (a = a.path,c = a.tl) && a.hd === "map" && (d = c.tl) && (a = d.tl) && a.nil?___map_screen_9f95c05e({lon:BslNumber_Float_of_string(d.hd),lat:BslNumber_Float_of_string(c.hd)},b):___login_screen_9f95c05e(b);};
global.___Controller_f20327e6 = {dispatcher:___dispatcher_f20327e6};
global.___resources_f20327e6 = BslCps_topwait(___StringMap_add_ec0784c7("resources/css/style.css",___static_include_resource_f20327e6,___StringMap_empty_ec0784c7,cont(BslCps_topk)));
var ____do__f20327e6 = function (){var a;return BslCps_topwait((a = {tl:{tl:{tl:{nil:js_void},hd:{dispatch:___dispatcher_f20327e6}},hd:{resources:___resources_f20327e6}},hd:{register:{tl:{tl:{tl:{nil:js_void},hd:{css:{tl:{nil:js_void},hd:"/resources/css/style.css"}}},hd:{js:{nil:js_void}}},hd:{doctype:{html5:js_void}}}}},___start_b970f080(___http_b970f080,a,cont(BslCps_topk))));}();
